shared:
  project_name: ~
  project_logo: ~

  preview_collection_label: "Previews"
  preview_nav_filter: true
  preview_paths: [test/components/previews]
  preview_display_options: {}
  preview_controller: "Lookbook::PreviewController"
  preview_template: lookbook/previews/preview
  preview_inspector:
  preview_embeds:
    enabled: true
    policy: SAMEORIGIN
    panels: false
    actions: []
    scenarios: []
    display_option_controls: true
  preview_layout: ~
  preview_disable_action_view_annotations: true
  preview_disable_action_view_partial_prefixes: true
  preview_type_default: view_component
  preview_sort_scenarios: false
  preview_disable_error_handling: true
  preview_single_pass_rendering: false

  page_collection_label: "Pages"
  page_nav_filter: false
  page_controller: "Lookbook::PageController"
  page_route: pages
  page_paths: [test/components/docs]
  page_extensions: [html.*, md.*]
  page_options: {}

  markdown_options:
    # TODO: specify new markdown options

  snippet_options:
    # TODO: specify new snippet highlighting options

  component_paths: [app/views, app/components]

  reload_on_change: ~
  lazy_load_previews_and_pages: false
  listen_paths: []
  listen_extensions: [rb, html.*]
  autoload_previews: true

  log_level: 2
  log_use_rails_logger: true

  experimental_features: []

  links:
    docs: https://v2.lookbook.build
    demo: https://v2-demo.lookbook.build
    repo: https://github.com/lookbook-hq/lookbook/tree/v2
