shared:
  project_name: ~
  project_logo: ~

  preview_collection_label: "Previews"
  preview_nav_filter: true
  preview_paths: [test/components/previews]
  preview_display_options: {}
  preview_controller: "Lookbook::PreviewController"
  preview_template: lookbook/previews/preview
  preview_inspector:
    main_panels: [preview, output]
    drawer_panels: [source, notes, params, "*"]
    sidebar_panels: [previews, pages]
  preview_embeds:
    enabled: true
    policy: SAMEORIGIN
    panels: false
    actions: []
    scenarios: []
    display_option_controls: true
  preview_layout: ~
  preview_disable_action_view_annotations: true
  preview_type_default: view_component
  preview_sort_scenarios: false
  preview_disable_error_handling: false

  page_collection_label: "Pages"
  page_nav_filter: false
  page_controller: "Lookbook::PageController"
  page_route: pages
  page_paths: [test/components/docs]
  page_extensions: [html.*, md.*]
  page_options: {}

  markdown_options:
    tables: true
    fenced_code_blocks: true
    disable_indented_code_blocks: true
    strikethrough: true
    highlight: true
    with_toc_data: true
    lax_spacing: true

  highlighter_options:
    theme: github
    dark: false

  component_paths: [app/views, app/components]

  reload_on_change: ~
  live_updates: false
  listen_paths: []
  listen_extensions: [rb, html.*]
  autoload_previews: true

  ui_theme: indigo
  ui_theme_overrides: {}
  ui_favicon: true

  log_level: 2
  log_use_rails_logger: true

  debug_menu: false

  links:
    docs: https://v2.lookbook.build
    demo: https://v2-demo.lookbook.build
    repo: https://github.com/ViewComponent/lookbook/tree/v2

development:
  debug_menu: true
  live_updates: true

test:
  debug_menu: true
  live_updates: false
